### ISSUE TITLE
Versions past 1.18.2 aren't listed in the header

### ISSUE THREAD

**Issue by embeddedt** [mcmodbrowser/mcmodbrowser.github.io#1]
You can still access pages for these versions by editing the URL (e.g. https://mcmodbrowser.github.io/modpacks/1.19.2.html) but you're unable to select them at the top of the page.

![image](https://github.com/mcmodbrowser/mcmodbrowser.github.io/assets/42941056/558df4df-4b6b-4d76-8eb3-d0e9992e61d4)

**Comment by makamys** [comment]
You can click the word `for` to expand the list. It's... not the most intuitive. I should probably revisit the design.
